resize: 240
imagesize: 240
resolution: 240
masksize: 240
batch_size: 5000
full_shot: true
k_shot: 4
backbone: ViT-B-16-plus-240
pretrained_dataset: laion400m_e32
meta_epochs: 100
n_ctx: 4
n_ctx_ab: 1
n_pro: 3
n_pro_ab: 4
lr: 0.002
momentum: 0.9
weight_decay: 0.0005
lambda1: 0.001
